model:
    arch: unet
data:
    dataset: pascal
    #train_split: train_aug
    train_split: train
    val_split: val
    img_rows: 256
    img_cols: 256
    #path: /private/home/meetshah/datasets/VOC/060817/VOCdevkit/VOC2012/
    path: ./datasets/GRAPE2020/
    #sbd_path: /private/home/meetshah/datasets/VOC/benchmark_RELEASE/
training:
    train_iters: 250  #50
    batch_size: 2
    val_interval: 500
    n_workers: 2
    print_interval: 25
    optimizer:
        #name: 'sgd'
        name: 'adam'     #beta,weigth_dacay等参数不用写，已经默认了
        lr: 1.0e-6
        #momentum: 0.99  #换成adam之后会报错,adam没有这个参数
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    #resume: fcn8s_pascal_best_model.pkl
    resume: unet_pascal_best_model.pkl
